name: "Building release binaries on MacOS"

on: [push]

jobs:
  Ubuntu1804-Build:
    name: Ubuntu1804
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build binary
        run: |
          set -e -o pipefail
          set -x
          mkdir artifact

          sudo apt-get update && sudo  apt-get dist-upgrade -y
          sudo apt-get install -y libusb-1.0.0-dev

          export PATH=$PATH:/usr/local/go/bin:~/go/bin
          if [[ ! -x $(command -v go ) ]]; then
            curl -o - https://golang.org/dl/go1.14.15.linux-amd64.tar.gz |\
              sudo tar -C /usr/local -xzvf -
          fi
          if [[ ! -x $(command -v go-bin-deb) ]]; then
            curl -L -o go-bin-deb.dpkg https://github.com/mh-cbon/go-bin-deb/releases/download/0.0.19/go-bin-deb-amd64.deb
            sudo dpkg -i go-bin-deb.dpkg
            sudo apt-get install --fix-missing
          fi

          make
          strip --strip-all bin/yubihsm-connector
          version=`bin/yubihsm-connector version`
          go-bin-deb generate -f deb/deb.json -a amd64 --version=${version}-1
          cp *.deb artifact

          ./bin/yubihsm-connector --help

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: yubihsm-connector-ubuntu1804-amd64
          path: artifact

  Ubuntu2004-Build:
    name: Ubuntu2004
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build binary
        run: |
          set -e -o pipefail
          set -x
          mkdir artifact

          sudo apt-get update && sudo  apt-get dist-upgrade -y
          sudo apt-get install -y libusb-1.0.0-dev

          export PATH=$PATH:/usr/local/go/bin:~/go/bin
          if [[ ! -x $(command -v go ) ]]; then
            curl -o - https://golang.org/dl/go1.14.15.linux-amd64.tar.gz |\
              sudo tar -C /usr/local -xzvf -
          fi
          if [[ ! -x $(command -v go-bin-deb) ]]; then
            curl -L -o go-bin-deb.dpkg https://github.com/mh-cbon/go-bin-deb/releases/download/0.0.19/go-bin-deb-amd64.deb
            sudo dpkg -i go-bin-deb.dpkg
            sudo apt-get install --fix-missing
          fi

          make
          strip --strip-all bin/yubihsm-connector
          version=`bin/yubihsm-connector version`
          go-bin-deb generate -f deb/deb.json -a amd64 --version=${version}-1
          cp *.deb artifact

          ./bin/yubihsm-connector --help

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: yubihsm-connector-ubuntu2004-amd64
          path: artifact